// react/crud-jsonServer/frontend/src/components/home/home.jsx
import React from "react"
import Main from "../template/Main"

export default props => 
 <Main icon="home" title="Início" subtitle="Segundo Projeto do capítulo do React">
    <div className="display-4">Bem-Vindo!</div>
    <hr/>
    <p className="mb-0">
        Sistema para exemplificar a construção de um cadastro
        desenvolvido em React!
    </p>
 </Main>

// angular/crud/frontend/src/app/views/home/home.component.ts
import { Component } from '@angular/core';
import { MatCardModule } from "@angular/material/card";
import { HeaderData } from '../../components/template/header/header-data';
import { HeaderService } from '../../components/template/header/header.service';

@Component({
  selector: 'app-home',
  standalone: true,
  imports:  [ MatCardModule ],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  
  constructor(private headerService: HeaderService){
    headerService.headerData = {
      title: "Início",
      icon: "home",
      routeUrl: ""
    }
  }


}

<mat-card class="home mat-elevation-z3">
    <mat-card-title class="title">Bem-vindo</mat-card-title>
    <mat-card-subtitle class="subtitle">
        Sistema para exemplificar a construção de um cadastro em Angular
    </mat-card-subtitle>
</mat-card>
